/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'freelancer' : null };
export interface Application {
  'jobId' : bigint,
  'proposal' : string,
  'freelancer' : Principal,
}
export interface FreelancerProfile {
  'id' : Principal,
  'bio' : string,
  'portfolio' : string,
  'name' : string,
  'hourlyRate' : bigint,
  'skills' : Array<string>,
}
export interface Job {
  'id' : bigint,
  'client' : Principal,
  'title' : string,
  'description' : string,
  'category' : string,
  'budget' : bigint,
  'requiredSkills' : Array<string>,
}
export interface PlatformStats {
  'totalJobs' : bigint,
  'totalUsers' : bigint,
  'totalApplications' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'role' : AppUserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptApplication' : ActorMethod<[bigint, Principal], undefined>,
  'applyToJob' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseFreelancersBySkill' : ActorMethod<[string], Array<FreelancerProfile>>,
  'browseJobsByCategory' : ActorMethod<[string], Array<Job>>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createJobPayment' : ActorMethod<[bigint, string, string], string>,
  'getAllFreelancersByName' : ActorMethod<[], Array<FreelancerProfile>>,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFreelancerProfile' : ActorMethod<[Principal], [] | [FreelancerProfile]>,
  'getJobApplications' : ActorMethod<[bigint], Array<Application>>,
  'getJobPaymentStatus' : ActorMethod<[bigint], [] | [string]>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'postJob' : ActorMethod<
    [string, string, bigint, Array<string>, string],
    undefined
  >,
  'registerClient' : ActorMethod<[string], undefined>,
  'registerFreelancer' : ActorMethod<
    [string, string, Array<string>, bigint, string],
    undefined
  >,
  'rejectApplication' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyJobPayment' : ActorMethod<[string], StripeSessionStatus>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];