/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FreelancerProfile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'portfolio' : IDL.Text,
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'client' : IDL.Principal,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'budget' : IDL.Nat,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AppUserRole = IDL.Variant({
  'client' : IDL.Null,
  'freelancer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : AppUserRole,
});
export const Application = IDL.Record({
  'jobId' : IDL.Nat,
  'proposal' : IDL.Text,
  'freelancer' : IDL.Principal,
});
export const PlatformStats = IDL.Record({
  'totalJobs' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptApplication' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseFreelancersBySkill' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FreelancerProfile)],
      ['query'],
    ),
  'browseJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createJobPayment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllFreelancersByName' : IDL.Func(
      [],
      [IDL.Vec(FreelancerProfile)],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFreelancerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(FreelancerProfile)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func([IDL.Nat], [IDL.Vec(Application)], ['query']),
  'getJobPaymentStatus' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'postJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'registerClient' : IDL.Func([IDL.Text], [], []),
  'registerFreelancer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'rejectApplication' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyJobPayment' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FreelancerProfile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'portfolio' : IDL.Text,
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'client' : IDL.Principal,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'budget' : IDL.Nat,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AppUserRole = IDL.Variant({
    'client' : IDL.Null,
    'freelancer' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppUserRole });
  const Application = IDL.Record({
    'jobId' : IDL.Nat,
    'proposal' : IDL.Text,
    'freelancer' : IDL.Principal,
  });
  const PlatformStats = IDL.Record({
    'totalJobs' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptApplication' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'applyToJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseFreelancersBySkill' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FreelancerProfile)],
        ['query'],
      ),
    'browseJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createJobPayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllFreelancersByName' : IDL.Func(
        [],
        [IDL.Vec(FreelancerProfile)],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFreelancerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(FreelancerProfile)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getJobPaymentStatus' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'postJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'registerClient' : IDL.Func([IDL.Text], [], []),
    'registerFreelancer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'rejectApplication' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyJobPayment' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  });
};

export const init = ({ IDL }) => { return []; };